language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - pypy

install:
  - python setup.py install
  - pip install coveralls nose nose-cov mock httmock testfixtures

script:
  - python setup.py test
  - nosetest --with-coverage

after_success:
  - coveralls

deploy:
  provider: pypi
  user: 2xyo
  password:
    secure: Jx8CqW06WOO8i7Fr/QycVRgLLth9HP90LWi1UqpUDKdvpBaqoF3RqBztpGRPZ4MuS2+FMMi4wLmGNdjzZeEF8WtAi3iKALhBQu0AJPtUTfga7swdUBv05i8IkKkEE0HyLR8KNKlAfyQ6ZYO289fNQT1lUuaxaKxrgVIeZ1Z9w6k=
  on:
    tags: true
